name: news_app_clean_architecture222
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.0
  intl: ^0.18.1
  floor: ^1.4.2
  retrofit: ^3.0.1
  flutter_hooks: ^0.18.3
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.2.0 # o la versión más reciente disponible
  floor_generator: ^1.2.0 # compatible con tu versión actual de SDK
  build_runner: ^2.4.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/muli/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
